CART_CREATED = "CART_CREATED"

ITEM_ADDED = "ITEM_ADDED"

ITEM_REMOVED = "ITEM_REMOVED"

QUANTITY_UPDATED = "QUANTITY_UPDATED"

CART_EMPTIED = "CART_EMPTIED"

CHECKOUT_COMPLETED = "CHECKOUT_COMPLETED"

ORDER_CANCELLED = "ORDER_CANCELLED"